#!/usr/bin/env ruby
 
who_cmd = "svn info -r HEAD | grep Author"
last_rev_alerted = 0
 
while(true)
  `svn info > /tmp/svn_uppity.local.txt`
  `svn info -r HEAD > /tmp/svn_uppity.remote.txt`
  rev = `diff /tmp/svn_uppity.local.txt /tmp/svn_uppity.remote.txt | grep Revision`
  if rev.size > 1
    rev =~ /^> Revision: (.+)$/
    rev = $1
    if rev != last_rev_alerted
      who = `#{who_cmd}`
      who =~ /^Last Changed Author: (.+)$/
      who = $1
      what = `svn log -r #{rev}`
      what = what.split("\n")
      what.pop
      what.shift; what.shift; what.shift
      what = what.join("\n")
 
      puts "New Revision #{rev} by #{who}\n\t#{what}\n"
      #`espeak "New Revision. Number #{rev}. Author #{who}."`
      notify_opts = [
       "--icon=/usr/share/icons/gnome/32x32/emblems/emblem-new.png",
       '"New Revision"',
       "\"#{rev} by #{who}\n\n#{what}\""
      ]
      # puts "notify-send #{notify_opts.join(' ')}"
      `notify-send #{notify_opts.join(' ')}`
      last_rev_alerted = rev
    end
  end
  sleep(180)
end
